extends BaseComponentData
class_name ContainerComponentData


@export var cargo_type: String
@export var faction_owner: Utility.FACTION

## Stores the exact world coordinates of uncollected containers.
@export var uncollected_positions: Array[Vector2] = []


func _init() -> void:
	# Set the specific ID so the Manager knows to spawn the ContainerComponent Node
	component_id = &"container"


## Helper to populate the data when generated by a mission or random event.
func setup_data(cargo: String, faction: Utility.FACTION, spawn_positions: Array[Vector2]) -> void:
	cargo_type = cargo
	faction_owner = faction
	uncollected_positions = spawn_positions


## Called by the View/World Node when a player collects a container.
func collect_container(pos: Vector2) -> void:
	# Safely removes this specific position from the array
	uncollected_positions.erase(pos) 
	
	if uncollected_positions.is_empty():
		complete()
		MissionManager.complete_mission()
